import { Router } from 'express';
import { adminRouter } from '../modules/admin/admin.routes.js';
import { applicationsRouter } from '../modules/applications/applications.routes.js';
import { authRouter } from '../modules/auth/auth.routes.js';
import { businessesRouter } from '../modules/businesses/businesses.routes.js';
import { candidatesRouter } from '../modules/candidates/candidates.routes.js';
import { cmsRouter } from '../modules/cms/cms.routes.js';
import { companiesRouter } from '../modules/companies/companies.routes.js';
import { cronRouter } from '../modules/cron/cron.routes.js';
import { jobsRouter } from '../modules/jobs/jobs.routes.js';
import { locationsRouter } from '../modules/locations/locations.routes.js';
import { notificationsRouter } from '../modules/notifications/notifications.routes.js';
import { packagesRouter } from '../modules/packages/packages.routes.js';
import { paymentsRouter } from '../modules/payments/payments.routes.js';
import { skillsRouter } from '../modules/skills/skills.routes.js';
import { ok } from '../utils/api-response.js';

export const apiRouter = Router();
apiRouter.get('/health', (_req, res) => ok(res, { service: 'jph-jobs-backend', status: 'ok' }, 'Healthy'));
apiRouter.use('/auth', authRouter);
apiRouter.use('/jobs', jobsRouter);
apiRouter.use('/companies', companiesRouter);
apiRouter.use('/businesses', businessesRouter);
apiRouter.use('/candidates', candidatesRouter);
apiRouter.use('/applications', applicationsRouter);
apiRouter.use('/packages', packagesRouter);
apiRouter.use('/payments', paymentsRouter);
apiRouter.use('/locations', locationsRouter);
apiRouter.use('/skills', skillsRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/cms', cmsRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/cron', cronRouter);
